services:
  db:
    container_name: postgresDb
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5333:5433"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: