#for disable the web server we can use `web-application-type: none`
server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/diary
    username: admin
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  main:
    web-application-type: servlet
